name: iptv

on:
  workflow_dispatch:
  schedule:
  - cron: '5 0 * * *'

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.BOT }}
    - name: Update
      run: |
        curl http://itv.22m.top/ITVBox/tv/tvonline.txt > box.txt
        git config --global user.name 'semi'
        git config --global user.email 'semi@zklink.org'
        if [ -z $(git status --porcelain) ];
        then
          echo "Updated"
        else
          git add box.txt
          git commit -m "Automate"
          git push
        fi
